// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9vL97isflgRT_ls_i-z6BcCYqXghLvcQ',
    appId: '1:226911814457:android:e259d7ce15e434af2c5ee8',
    messagingSenderId: '226911814457',
    projectId: 'brian--flutter-mynotes',
    storageBucket: 'brian--flutter-mynotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA90uGIv8avQdnbx4RGvl5ssfCgmkzYvsE',
    appId: '1:226911814457:ios:94eaf8396e1368a92c5ee8',
    messagingSenderId: '226911814457',
    projectId: 'brian--flutter-mynotes',
    storageBucket: 'brian--flutter-mynotes.appspot.com',
    iosClientId: '226911814457-a1gokgn2l7dd2f83u1421eq76vg0oo4s.apps.googleusercontent.com',
    iosBundleId: 'com.brianyau.mynotes',
  );
}
